### PR TITLE
REL sentence-transformers 3.1.0

### PR DESCRIPTION
**Pull request by glemaitre**
closes #41

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by glemaitre** [comment]
@conda-forge-admin, please rerender

**Comment by glemaitre** [comment]
@ndmaxar @oblute @rluria14 @sugatoray The bot to release 3.1.0 failed in #41.
Could you have a look to see if the recipe is what you would expect.

**Comment by glemaitre** [comment]
@conda-forge-admin, please rerender

**Comment by sugatoray** [comment]
Closing this PR as an advanced version was merged via PR #43. 

cc: @glemaitre

**Pull request closed without merging**
